// User Info
export const AGE_SET = 'AGE_SET';
export const GENDER_SET = 'GENDER_SET';
export const SKIN_COLOR_SET = 'SKIN_COLOR_SET';
export const SKIN_TYPE_SET = 'SKIN_TYPE_SET';
export const CLIMATE_SET = 'CLIMATE_SET';
export const USER_INPUTS_POST_SUCCESS = 'USER_INPUTS_POST_SUCCESS';
export const USER_INPUTS_POST_PENDING = 'USER_INPUTS_POST_PENDING';
export const USER_INPUTS_POST_FAIL = 'USER_INPUTS_POST_FAIL';
