// User Info
export const AGE_SET = 'AGE_SET';
export const GENDER_SET = 'GENDER_SET';
export const SKIN_COLOR_SET = 'SKIN_COLOR_SET';
export const SKIN_TYPE_SET = 'SKIN_TYPE_SET';
export const CLIMATE_SET = 'CLIMATE_SET';
export const USER_INPUTS_POST = 'USER_INPUTS_POST';

export const EMAIL_SET = 'EMAIL_SET';
export const PASSWORD_SET = 'PASSWORD_SET';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_PENDING = 'SIGNIN_PENDING';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';

export const RECORD_DETAIL_MODAL_OPEN = 'RECORD_DETAIL_MODAL_OPEN';
export const RECORD_DETAIL_MODAL_CLOSE = 'RECORD_DETAIL_MODAL_CLOSE';

export const PRODUCT_DETAIL_MODAL_OPEN = 'PRODUCT_DETAIL_MODAL_OPEN';
export const PRODUCT_DETAIL_MODAL_CLOSE = 'PRODUCT_DETAIL_MODAL_CLOSE';

export const OTHER_USER_PROFILE_MODAL_OPEN = 'OTHER_USER_PROFILE_MODAL_OPEN';
export const OTHER_USER_PROFILE_MODAL_CLOSE = 'OTHER_USER_PROFILE_MODAL_CLOSE';

export const MY_PROFILE_GET = 'MY_PROFILE_GET';
export const OTHER_USER_PROFILE_GET = 'OTHER_USER_PROFILE_GET';

export const SUCCESS = 'SUCCESS';
export const PENDING = 'PENDING';
export const FAIL = 'FAIL';

export const RECORD_POST = 'RECORD_POST';
export const RECORDS_GET = 'RECORDS_GET';
export const CURRENT_RECORD_SET = 'CURRENT_RECORD_SET';

export const CATEGORIES_GET = 'CATEGORIES_GET';
export const CATEGORY_SET = 'CATEGORY_SET';

export const CURRENT_PRODUCT_SET = 'CURRENT_PRODUCT_SET';

export const TAG_FILTER_SET = 'TAG_FILTER_SET';

export const START_SCANNING_ANIMATION = 'START_SCANNING_ANIMATION';
export const STOP_SCANNING_ANIMATION = 'STOP_SCANNING_ANIMATION';

export const FAVORITE_PRODUCT_ADD = 'FAVORITE_PRODUCT_ADD';
export const FAVORITE_PRODUCT_REMOVE = 'FAVORITE_PRODUCT_REMOVE';

export const ADD_FAVORITE_PRODUCT_SUCCESS_MODAL_CLOSE =
  'ADD_FAVORITE_PRODUCT_SUCCESS_MODAL_CLOSE';
export const REMOVE_FAVORITE_PRODUCT_SUCCESS_MODAL_CLOSE =
  'REMOVE_FAVORITE_PRODUCT_SUCCESS_MODAL_CLOSE';

export const MARK_REVIEW_HELPFUL = 'MARK_REVIEW_HELPFUL';
export const UNMARK_REVIEW_HELPFUL = 'UNMARK_REVIEW_HELPFUL';
export const REVIEW_POST = 'REVIEW_POST';

export const POST_REVIEW_SUCCESS_MODAL_CLOSE =
  'POST_REVIEW_SUCCESS_MODAL_CLOSE';

export const RECOMMENDED_PRODUCTS_GET = 'RECOMMENDED_PRODUCTS_GET';
