// User Info
export const AGE_SET = 'AGE_SET';
export const GENDER_SET = 'GENDER_SET';
export const SKIN_COLOR_SET = 'SKIN_COLOR_SET';
export const SKIN_TYPE_SET = 'SKIN_TYPE_SET';
export const CLIMATE_SET = 'CLIMATE_SET';
export const USER_INPUTS_POST_SUCCESS = 'USER_INPUTS_POST_SUCCESS';
export const USER_INPUTS_POST_PENDING = 'USER_INPUTS_POST_PENDING';
export const USER_INPUTS_POST_FAIL = 'USER_INPUTS_POST_FAIL';

export const EMAIL_SET = 'EMAIL_SET';
export const PASSWORD_SET = 'PASSWORD_SET';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_PENDING = 'SIGNIN_PENDING';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';

export const RECORD_DETAIL_MODAL_OPEN = 'RECORD_DETAIL_MODAL_OPEN';
export const RECORD_DETAIL_MODAL_CLOSE = 'RECORD_DETAIL_MODAL_CLOSE';
